### ISSUE TITLE
dtmf

### ISSUE THREAD

**Issue by atulgo** [angryelectron/fona#1]
Detection of DTMF tones - SIM800L module.

I get "OK" when I send 'AT+DDET=1,1000,1,1* ' over uart .
But it doesnt seem to detect anything afterwards.
Perhaps I am doing something wrong.
Would appreciate some feedback.

regards
Atul
ref : *SIM800 Series_AT Command Manual_V1.09

**Comment by abythell** [comment]
This library doesn't support DDET unsolicited messages, so I assume your question is a general one.

What response do you receive from the DDET test and read commands?  I'm not sure about the * at the end of your write command.  What happens when you write 1,0,1,1 ?

Sorry I can't give you specifics, I haven't played with a SIM800 in a few years.

**Comment by atulgo** [comment]
Thanks for the reply Abythell.
I used -
AT+DDET=1,100,1,1\r
got reply -
OK
but it does seem an issue at operator end.
Regards
